---
title: "Day 2 tasks"
author: "Eva Newby"
format: html
editor: visual
editor_options: 
  chunk_output_type: console
---

## 

```{r}

# find the slope of f(x)=x2 at x=3 ----
eq1 <- function(x) {
  x^2
}

deriv_eq1 <- D(expr = expression(x^2), name = "x")

deriv_eq1_fun <- function(x) {
  2 * x
}
deriv_eq1_fun(3)

```

# find the slope of pa ----

```{r}
eq2 <-function(a){2*(3*a+2)^4 -5}

deriv_eq2 <- D(expr = expression (2*(3*a+2)^4 -5), name = "a")
 deriv_eq2

 deriv_eq2_fun <- function(a) {
   2 * (4 * (3 * (3 * a + 2)^3))
 }
 
 deriv_eq2_fun(1.2)
``` 

# Section 3 - Penguin plot

```{r}
library(tidyverse)
library(palmerpenguins)

data(package='palmerpenguins')
penguins <- penguins

ggplot(data = penguins, aes(x = bill_depth_mm, y = bill_length_mm, color = species))+
  geom_point()+
  ggtitle("Penguin Bill Length in relation to Penguin Bill Depth")+
  xlab("Bill Depth (in millimeters)") 

```

```{r}
ggplot(data = penguins, aes(x = species, y = flipper_length_mm, color = species)) +
  geom_jitter()+ggtitle("Flipper Length by Penguin Species") + 
  xlab("Penguin Species") + 
  ylab("Flipper Length (in mm)")


```


